### ISSUE TITLE
story(sbb-checkbox): Alternative solution for removing white space underneath inline-block elements

### ISSUE THREAD

**Issue by dauriamarco** [lyne-design-system/lyne-components#1465]
### Feature Description

We would like to have a fallback solution for the white space issue with inline-block components. A possible approach could be the following:

```htm
<label class="wrapper" htmlFor={this.checkboxId}>
  <input
    type="checkbox"
    id={this.checkboxId}
    checked={this.checked}
    value={this.value}
    onChange={(event: Event): void => this.checkedChanged(event)}
  />
  <span class="checkbox"></span>
  <div class="label">Lorem ipsum dolor sit amet.</div>
  <span class="icon"></span>
</label>
```

```scss
.wrapper {
  display: flex;
  position: relative;
  width: 100%; //if icon-pacement equals to "end"
}

.checkbox {
  position: absolute;
  width: 24px;
  height: 24px;
  border: 1px solid black;

  :host([checked]) & {
    //checked style
  }
}

.label {
  font-size: 14px;
  padding-inline: 2rem;
  display: inline;
  box-decoration-break: clone; //to apply padding to all lines
  width: 100%; //if icon-pacement equals to "end"
}

.icon {
  position: absolute;
  right: 0;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background-color: black;
}
```

### Definition of Done

- [ ] The implementation is tested with all variants of the specs
