### ISSUE TITLE
Find solution to prevent FOUT of CSR (encapsulated web components aka default mode)

### ISSUE THREAD

**Issue by 4aficiona2** [lyne-design-system/lyne-components#823]
## Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/.github/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Summary
Since there is not a globally defined CSS (except the font-face declartaion) for all encapsulated components (default mode for Lyne Components) the default text styling falls back to the default browser font e.g. Times New Roman (serif) which then leads to a FOUT (flash of unstyled text) once the components CSS is loaded.

#### Possible solutions

These solutions would be part of the suggested `lyne-fonts` npm package and the SBB font-face declaration would go first in this CSS file.

##### Generic
```css
body {
  font-family: "SBBWeb Roman", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

Pro: Fairly easy
Cons: Side effects (on all typography) because it is very generic

##### Attribute selector e.g.
```css
[lyne-*] {
  font-family: "SBBWeb Roman", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

Pro: less generic, only applies to components which have this attribute. Components need to have all this shared attribute since there is no wildcard selector for tags like `lyne-*`
Cons: Introduction of a attribute over all components
